# Generated by Django 5.2 on 2025-05-12 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_resumeanalysis_resume_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
                ('required_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
        ),
        migrations.CreateModel(
            name='MatchedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matching_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_jobs', to='app.resume')),
            ],
            options={
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
