# Generated by Django 5.2 on 2025-05-12 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_alter_resume_job_titles_alter_resume_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.resume'),
        ),
    ]
