# Generated by Django 5.2 on 2025-05-12 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_handle_existing_data'),
        ('app', '0004_resumeanalysis_updated_at_and_more'),
    ]

    operations = [
    ]
